config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "messages#index"
  resources :messages

  # match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :default_role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    self.role == "admin"
  end
  private

  def default_role
    self.role = "user"
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protected
    def authenticate_admin
        unless current_user.admin?
            flash[:alert] = "You cannot perform this action"
            redirect_to root_path
        end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!, :except => [:index]
    before_action :authenticate_admin, :only => [:destroy]
    def index
        @messages = Message.order(created_at: :desc).page(params[:page]).per(5)
        # @messages = @messages.sort_by { |m| m.created_at }.reverse
    end

    def new
        @message = Message.new
    end

    def create
        @message = Message.new(message_params)
        @message.save
        redirect_to messages_path
    end 

    def destroy
        @message = Message.find(params[:id])
        @message.destroy
        flash[:notice] = "Message Deleted."
        redirect_to messages_path
    end

    private

    def message_params
        params.require(:message).permit(:author, :msg)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MsgBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1> Message Board </h1>

<% if current_user %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %> |
    <%= link_to('Change Password', edit_registration_path(:user)) %>
<% else %>
    <%= link_to('Register', new_registration_path(:user)) %> |
    <%= link_to('Login', new_session_path(:user)) %>
<% end %>

<br>

<%= paginate @messages %>

<% @messages.each do |message| %>

    <%= message.author %>
    <%= message.created_at %>
    <% if current_user && current_user.role == 'admin'%>
        <%= link_to "Delete", message_path(message), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <% end %>
    <p><%= message.msg %></p>
    
<% end %>

<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h1> New Message </h1>

<%= form_for @message, :url => { :controller => 'messages', :action => "create" } do |f| %>
    <%= f.label :author, "Author" %>
    <%= f.text_field :author %>
    <br>
    <%= f.label :msg, "Message" %>
    <%= f.text_area :msg %>
    <br>
    <%= f.submit "Submit"%>
<% end %>